// <auto-generated />
using System;
using HotelChecklist.Api.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelChecklist.Api.Common.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924131953_DropChecklistTemplateEstimatedDuration")]
    partial class DropChecklistTemplateEstimatedDuration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelChecklist.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_areas");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_areas_name");

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_assets_area_id");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.Call", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_calls");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_calls_area_id");

                    b.HasIndex("AssignedUserId")
                        .HasDatabaseName("ix_calls_assigned_user_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_calls_created_by_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_calls_status");

                    b.ToTable("calls", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_checklist_instances");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_checklist_instances_status");

                    b.HasIndex("AssetId", "Date")
                        .HasDatabaseName("ix_checklist_instances_asset_id_date");

                    b.HasIndex("TemplateId", "AssetId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_checklist_instances_template_id_asset_id_date");

                    b.ToTable("checklist_instances", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("execution_mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_checklist_tasks");

                    b.HasIndex("TemplateId", "Order")
                        .HasDatabaseName("ix_checklist_tasks_template_id_order");

                    b.ToTable("checklist_tasks", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTaskEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChecklistTaskExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("checklist_task_execution_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_checklist_task_evidences");

                    b.HasIndex("ChecklistTaskExecutionId")
                        .HasDatabaseName("ix_checklist_task_evidences_checklist_task_execution_id");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_checklist_task_evidences_uploaded_by_user_id");

                    b.ToTable("checklist_task_evidences", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTaskExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<Guid>("ChecklistInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("checklist_instance_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid?>("ExecutedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("executed_by_user_id");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateTimeOffset?>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for_utc");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_checklist_task_executions");

                    b.HasIndex("ApprovedByUserId")
                        .HasDatabaseName("ix_checklist_task_executions_approved_by_user_id");

                    b.HasIndex("AssignedUserId")
                        .HasDatabaseName("ix_checklist_task_executions_assigned_user_id");

                    b.HasIndex("ChecklistInstanceId")
                        .HasDatabaseName("ix_checklist_task_executions_checklist_instance_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_checklist_task_executions_created_by_user_id");

                    b.HasIndex("ExecutedByUserId")
                        .HasDatabaseName("ix_checklist_task_executions_executed_by_user_id");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_checklist_task_executions_schedule_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_checklist_task_executions_task_id");

                    b.HasIndex("ChecklistInstanceId", "TaskId")
                        .HasDatabaseName("ix_checklist_task_executions_checklist_instance_id_task_id");

                    b.ToTable("checklist_task_executions", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("created_by_role");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("execution_mode");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsSnapshot")
                        .HasColumnType("boolean")
                        .HasColumnName("is_snapshot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_checklist_templates");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_checklist_templates_area_id");

                    b.HasIndex("GroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_checklist_templates_group_id")
                        .HasFilter("is_snapshot = false");

                    b.HasIndex("GroupId", "IsSnapshot")
                        .HasDatabaseName("ix_checklist_templates_group_id_is_snapshot");

                    b.ToTable("checklist_templates", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_month");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("integer")
                        .HasColumnName("execution_order");

                    b.Property<string>("FrequencyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frequency_type");

                    b.Property<int>("IntervalValue")
                        .HasColumnType("integer")
                        .HasColumnName("interval_value");

                    b.Property<TimeOnly>("TimeOfDay")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_of_day");

                    b.Property<string>("WeekDay")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("week_day");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.HasIndex("FrequencyType", "Active")
                        .HasDatabaseName("ix_schedules_frequency_type_active");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.TaskSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_task_schedules");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_task_schedules_schedule_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_schedules_task_id");

                    b.ToTable("task_schedules", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.TemplateAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_template_assets");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_template_assets_asset_id");

                    b.HasIndex("TemplateId", "AssetId")
                        .IsUnique()
                        .HasDatabaseName("ix_template_assets_template_id_asset_id");

                    b.ToTable("template_assets", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.TemplateSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_template_schedules");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_template_schedules_schedule_id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_template_schedules_template_id");

                    b.ToTable("template_schedules", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.UserArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_areas");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_user_areas_area_id");

                    b.HasIndex("UserId", "AreaId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_areas_user_id_area_id");

                    b.ToTable("user_areas", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.Asset", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.Area", "Area")
                        .WithMany("Assets")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assets_areas_area_id");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.Call", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calls_areas_area_id");

                    b.HasOne("HotelChecklist.Domain.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_calls_users_assigned_user_id");

                    b.HasOne("HotelChecklist.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_calls_users_created_by_user_id");

                    b.Navigation("Area");

                    b.Navigation("AssignedUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistInstance", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.Asset", "Asset")
                        .WithMany("ChecklistInstances")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_instances_assets_asset_id");

                    b.HasOne("HotelChecklist.Domain.Entities.ChecklistTemplate", "Template")
                        .WithMany("Instances")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_instances_checklist_templates_template_id");

                    b.Navigation("Asset");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTask", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.ChecklistTemplate", "Template")
                        .WithMany("Tasks")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_tasks_checklist_templates_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTaskEvidence", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.ChecklistTaskExecution", "ChecklistTaskExecution")
                        .WithMany("Evidences")
                        .HasForeignKey("ChecklistTaskExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_task_evidences_checklist_task_executions_checklis");

                    b.HasOne("HotelChecklist.Domain.Entities.User", "UploadedByUser")
                        .WithMany("UploadedEvidences")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_task_evidences_users_uploaded_by_user_id");

                    b.Navigation("ChecklistTaskExecution");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTaskExecution", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_checklist_task_executions_users_approved_by_user_id");

                    b.HasOne("HotelChecklist.Domain.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_checklist_task_executions_users_assigned_user_id");

                    b.HasOne("HotelChecklist.Domain.Entities.ChecklistInstance", "ChecklistInstance")
                        .WithMany("TaskExecutions")
                        .HasForeignKey("ChecklistInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_task_executions_checklist_instances_checklist_ins");

                    b.HasOne("HotelChecklist.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_checklist_task_executions_users_created_by_user_id");

                    b.HasOne("HotelChecklist.Domain.Entities.User", "ExecutedByUser")
                        .WithMany()
                        .HasForeignKey("ExecutedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_checklist_task_executions_users_executed_by_user_id");

                    b.HasOne("HotelChecklist.Domain.Entities.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_checklist_task_executions_schedules_schedule_id");

                    b.HasOne("HotelChecklist.Domain.Entities.ChecklistTask", "Task")
                        .WithMany("Executions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_task_executions_checklist_tasks_task_id");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("AssignedUser");

                    b.Navigation("ChecklistInstance");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ExecutedByUser");

                    b.Navigation("Schedule");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.Area", "Area")
                        .WithMany("ChecklistTemplates")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_templates_areas_area_id");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.TaskSchedule", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_schedules_schedules_schedule_id");

                    b.HasOne("HotelChecklist.Domain.Entities.ChecklistTask", "Task")
                        .WithMany("TaskSchedules")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_schedules_checklist_tasks_task_id");

                    b.Navigation("Schedule");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.TemplateAsset", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_template_assets_assets_asset_id");

                    b.HasOne("HotelChecklist.Domain.Entities.ChecklistTemplate", "Template")
                        .WithMany("TemplateAssets")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_assets_checklist_templates_template_id");

                    b.Navigation("Asset");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.TemplateSchedule", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_schedules_schedules_schedule_id");

                    b.HasOne("HotelChecklist.Domain.Entities.ChecklistTemplate", "Template")
                        .WithMany("TemplateSchedules")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_schedules_checklist_templates_template_id");

                    b.Navigation("Schedule");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.UserArea", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_areas_areas_area_id");

                    b.HasOne("HotelChecklist.Domain.Entities.User", "User")
                        .WithMany("UserAreas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_areas_users_user_id");

                    b.Navigation("Area");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.Area", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("ChecklistTemplates");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.Asset", b =>
                {
                    b.Navigation("ChecklistInstances");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistInstance", b =>
                {
                    b.Navigation("TaskExecutions");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTask", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("TaskSchedules");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTaskExecution", b =>
                {
                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Navigation("Instances");

                    b.Navigation("Tasks");

                    b.Navigation("TemplateAssets");

                    b.Navigation("TemplateSchedules");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.User", b =>
                {
                    b.Navigation("UploadedEvidences");

                    b.Navigation("UserAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
