// <auto-generated />
using System;
using HotelChecklist.Api.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelChecklist.Api.Common.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelChecklist.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_areas");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_areas_name");

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_assets_area_id");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_checklist_instances");

                    b.HasIndex("ApprovedByUserId")
                        .HasDatabaseName("ix_checklist_instances_approved_by_user_id");

                    b.HasIndex("AssignedUserId")
                        .HasDatabaseName("ix_checklist_instances_assigned_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_checklist_instances_status");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_checklist_instances_template_id");

                    b.HasIndex("AssetId", "Date")
                        .HasDatabaseName("ix_checklist_instances_asset_id_date");

                    b.ToTable("checklist_instances", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_checklist_tasks");

                    b.HasIndex("TemplateId", "Order")
                        .HasDatabaseName("ix_checklist_tasks_template_id_order");

                    b.ToTable("checklist_tasks", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTaskEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChecklistTaskExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("checklist_task_execution_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_checklist_task_evidences");

                    b.HasIndex("ChecklistTaskExecutionId")
                        .HasDatabaseName("ix_checklist_task_evidences_checklist_task_execution_id");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_checklist_task_evidences_uploaded_by_user_id");

                    b.ToTable("checklist_task_evidences", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTaskExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChecklistInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("checklist_instance_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("pk_checklist_task_executions");

                    b.HasIndex("ChecklistInstanceId")
                        .HasDatabaseName("ix_checklist_task_executions_checklist_instance_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_checklist_task_executions_task_id");

                    b.ToTable("checklist_task_executions", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("RecurrenceType")
                        .HasColumnType("integer")
                        .HasColumnName("recurrence_type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_checklist_templates");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_checklist_templates_area_id");

                    b.ToTable("checklist_templates", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.Asset", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.Area", "Area")
                        .WithMany("Assets")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assets_areas_area_id");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistInstance", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.User", "ApprovedByUser")
                        .WithMany("ApprovedInstances")
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_checklist_instances_users_approved_by_user_id");

                    b.HasOne("HotelChecklist.Domain.Entities.Asset", "Asset")
                        .WithMany("ChecklistInstances")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_instances_assets_asset_id");

                    b.HasOne("HotelChecklist.Domain.Entities.User", "AssignedUser")
                        .WithMany("AssignedInstances")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_checklist_instances_users_assigned_user_id");

                    b.HasOne("HotelChecklist.Domain.Entities.ChecklistTemplate", "Template")
                        .WithMany("Instances")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_instances_checklist_templates_template_id");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Asset");

                    b.Navigation("AssignedUser");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTask", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.ChecklistTemplate", "Template")
                        .WithMany("Tasks")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_tasks_checklist_templates_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTaskEvidence", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.ChecklistTaskExecution", "ChecklistTaskExecution")
                        .WithMany("Evidences")
                        .HasForeignKey("ChecklistTaskExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_task_evidences_checklist_task_executions_checklis");

                    b.HasOne("HotelChecklist.Domain.Entities.User", "UploadedByUser")
                        .WithMany("UploadedEvidences")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_task_evidences_users_uploaded_by_user_id");

                    b.Navigation("ChecklistTaskExecution");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTaskExecution", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.ChecklistInstance", "ChecklistInstance")
                        .WithMany("TaskExecutions")
                        .HasForeignKey("ChecklistInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_task_executions_checklist_instances_checklist_ins");

                    b.HasOne("HotelChecklist.Domain.Entities.ChecklistTask", "Task")
                        .WithMany("Executions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_task_executions_checklist_tasks_task_id");

                    b.Navigation("ChecklistInstance");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.HasOne("HotelChecklist.Domain.Entities.Area", "Area")
                        .WithMany("ChecklistTemplates")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_templates_areas_area_id");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.Area", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("ChecklistTemplates");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.Asset", b =>
                {
                    b.Navigation("ChecklistInstances");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistInstance", b =>
                {
                    b.Navigation("TaskExecutions");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTask", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTaskExecution", b =>
                {
                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Navigation("Instances");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("HotelChecklist.Domain.Entities.User", b =>
                {
                    b.Navigation("ApprovedInstances");

                    b.Navigation("AssignedInstances");

                    b.Navigation("UploadedEvidences");
                });
#pragma warning restore 612, 618
        }
    }
}
